### PR TITLE
Corrected sum of n natural number

### PR DESCRIPTION
**Pull request by shreyas098**
Fixed errors of sum of n natural numbers

### CODE REVIEW

**Comment by shreyas098** [comment]
@Piyush-pk02  Can i request for this please?

**Comment by bhaveshraj336** [comment]
@shreyas098  i think i have resolved it so its giving a conflicts

**Comment by shreyas098** [comment]
I have add more abstract part to it . Please check @bhaveshraj336

**Comment by bhaveshraj336** [comment]
I can't @shreyas098

**Comment by shreyas098** [comment]
@eeshita19 can you please review it?

**Comment by shreyas098** [comment]
No worries @bhaveshraj336

**Pull request merged**
